In [ ]:

#  The Fuction Transforam is a tool scikit-learn a populer python libary
#  for machine learning that allows you to apply a specified to the input da
# the Fuction Transform can be usful for performing custom
# transforaam of input data in a machine learnin pipelne

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
X = np.array([[1, 2], [3, 4]])

# define the transformation function
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
X_transformed = log_transform.transform(X)

# view the transformed data
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [7]:
# Practical usecases
# 1. Custom Feature Engineering

from sklearn.preprocessing import FunctionTransformer
import numpy as np
# create a dataset
x = np.array([[1,2],[3,4]])

#define a custom feature engineering fuction
def my_feature_engineer(x):
  return np.hstack((x,x**2))
# create the FuctionTransformer to apply the custo fuction
custom_transformer = FunctionTransformer(my_feature_engineer)

# apply the transformer to the input data
x_transformed = custom_transformer.transform(x)

# view the transformed
print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [8]:
  # 2. Scaling And Normalization


from sklearn.preprocessing import FunctionTransformer
import numpy as np

x =np.array([[1,2],[3,4]])

def my_scaling(x):
     return x/np.max(x)
custom_transformer =FunctionTransformer(my_scaling)
x_transformed = custom_transformer.transform(x)
print(x_transformed)


[[0.25 0.5 ]
 [0.75 1.  ]]


In [11]:
# 3. Data Cleaning

from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset with missing values
X = np.array([[1,2],[3,np.nan]])

# define a custom cleaning fuction
def my_cleaning(X):
    X[np.isnan(X)]= 0
    return X

# create a FuctionTransformer to apply the custom fuction
custom_transformer = FunctionTransformer(my_cleaning)

# apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

# view the transformed data
print(X_transformed)




[[1. 2.]
 [3. 0.]]
